-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--   http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

CREATE TABLE IF NOT EXISTS client_ssh_configs
(
    tenant_id                  VARCHAR(255) NOT NULL,
    client_id                  VARCHAR(255) NOT NULL,
    client_secret              VARCHAR(512) NOT NULL,
    target_host                VARCHAR(255) NOT NULL,
    target_port                INT          NOT NULL DEFAULT 22,
    max_ttl_seconds            INT          NOT NULL DEFAULT 86400,
    allowed_key_types          JSONB         NOT NULL,
    source_address_restriction VARCHAR(255) NULL,
    denied_extensions          JSONB         NULL,
    principal_source           VARCHAR(20)  NOT NULL DEFAULT 'noop',
    enabled                    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at                 TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at                 TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (tenant_id, client_id)
);
CREATE INDEX IF NOT EXISTS idx_client_configs_enabled ON client_ssh_configs (enabled);
CREATE INDEX IF NOT EXISTS idx_client_configs_target_host ON client_ssh_configs (target_host);

CREATE TABLE IF NOT EXISTS certificate_issuance_logs
(
    id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id              VARCHAR(255) NOT NULL,
    client_id              VARCHAR(255) NOT NULL,
    serial_number          BIGINT       NOT NULL,
    key_id                 VARCHAR(255) NOT NULL,
    principal              VARCHAR(255) NOT NULL,
    user_email             VARCHAR(255) NULL,
    public_key_fingerprint VARCHAR(255) NOT NULL,
    ca_fingerprint         VARCHAR(255) NOT NULL,
    valid_after            TIMESTAMPTZ(6) NOT NULL,
    valid_before           TIMESTAMPTZ(6) NOT NULL,
    issued_at              TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    source_ip              VARCHAR(45)  NULL,
    granted_extensions     JSONB         NOT NULL,
    force_command          TEXT         NULL,
    user_access_token_hash VARCHAR(255) NULL,
    request_metadata       JSONB         NULL,

    PRIMARY KEY (id),
    CONSTRAINT uq_issuance_serial UNIQUE (serial_number)
);
CREATE INDEX IF NOT EXISTS idx_issuance_tenant_client ON certificate_issuance_logs (tenant_id, client_id);
CREATE INDEX IF NOT EXISTS idx_issuance_keyid ON certificate_issuance_logs (key_id);
CREATE INDEX IF NOT EXISTS idx_issuance_principal ON certificate_issuance_logs (principal);
CREATE INDEX IF NOT EXISTS idx_issuance_user_email ON certificate_issuance_logs (user_email);
CREATE INDEX IF NOT EXISTS idx_issuance_ca_fingerprint ON certificate_issuance_logs (ca_fingerprint);
CREATE INDEX IF NOT EXISTS idx_issuance_issued_at ON certificate_issuance_logs (issued_at);
CREATE INDEX IF NOT EXISTS idx_issuance_valid_range ON certificate_issuance_logs (valid_after, valid_before);

CREATE TABLE IF NOT EXISTS revocation_events
(
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id      VARCHAR(255) NOT NULL,
    client_id      VARCHAR(255) NOT NULL,
    serial_number  BIGINT       NULL,
    key_id         VARCHAR(255) NULL,
    ca_fingerprint VARCHAR(255) NULL,
    revoked_at     TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    reason         VARCHAR(255) NOT NULL,
    revoked_by     VARCHAR(255) NOT NULL,

    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_revocation_tenant_client ON revocation_events (tenant_id, client_id);
CREATE INDEX IF NOT EXISTS idx_revocation_serial ON revocation_events (serial_number);
CREATE INDEX IF NOT EXISTS idx_revocation_keyid ON revocation_events (key_id);
CREATE INDEX IF NOT EXISTS idx_revocation_ca_fingerprint ON revocation_events (ca_fingerprint);
CREATE INDEX IF NOT EXISTS idx_revocation_revoked_at ON revocation_events (revoked_at);

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END $$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_client_ssh_configs_updated_at
    BEFORE UPDATE ON client_ssh_configs
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
