/*
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

CREATE TABLE IF NOT EXISTS GATEWAY (
  CUSTOS_INTERNAL_GATEWAY_ID varchar(255) NOT NULL,
  DECLINED_REASON varchar(255) DEFAULT NULL,
  GATEWAY_DOMAIN varchar(255) DEFAULT NULL,
  EMAIL_ADDRESS varchar(255) DEFAULT NULL,
  GATEWAY_ACRONYM varchar(255) DEFAULT NULL,
  GATEWAY_ADMIN_EMAIL varchar(255) DEFAULT NULL,
  GATEWAY_ADMIN_FIRST_NAME varchar(255) DEFAULT NULL,
  GATEWAY_ADMIN_LAST_NAME varchar(255) DEFAULT NULL,
  GATEWAY_APPROVAL_STATUS varchar(255) DEFAULT NULL,
  GATEWAY_ID varchar(255) DEFAULT NULL,
  GATEWAY_NAME varchar(255) DEFAULT NULL,
  GATEWAY_PUBLIC_ABSTRACT varchar(255) DEFAULT NULL,
  GATEWAY_URL varchar(255) DEFAULT NULL,
  IDENTITY_SERVER_PASSWORD_TOKEN varchar(255) DEFAULT NULL,
  IDENTITY_SERVER_USERNAME varchar(255) DEFAULT NULL,
  OAUTH_CLIENT_ID varchar(255) DEFAULT NULL,
  OAUTH_CLIENT_SECRET varchar(255) DEFAULT NULL,
  REQUEST_CREATION_TIME bigint(20) DEFAULT NULL,
  REQUESTER_USERNAME varchar(255) DEFAULT NULL,
  GATEWAY_REVIEW_PROPOSAL_DESCRIPTION varchar(255) DEFAULT NULL,
  PRIMARY KEY (CUSTOS_INTERNAL_GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS USER_PROFILE (
    USER_ID VARCHAR (255) NOT NULL,
    GATEWAY_ID VARCHAR (255) NOT NULL,
    USER_MODEL_VERSION VARCHAR (255),
    FIRST_NAME VARCHAR (255),
    LAST_NAME VARCHAR (255),
    MIDDLE_NAME VARCHAR (255),
    NAME_PREFIX VARCHAR (255),
    NAME_SUFFIX VARCHAR (255),
    ORCID_ID VARCHAR (255),
    COUNTRY VARCHAR (255),
    HOME_ORGANIZATION VARCHAR (255),
    ORIGINATION_AFFILIATION VARCHAR (255),
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_ACCESS_TIME TIMESTAMP,
    VALID_UNTIL DATETIME,
    STATE VARCHAR (255),
    COMMENTS TEXT,
    GPG_KEY TEXT,
    TIME_ZONE VARCHAR (255),
    PRIMARY KEY (USER_ID, GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS USER_PROFILE_EMAIL (
    USER_ID VARCHAR (255) NOT NULL,
    GATEWAY_ID VARCHAR (255) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL,
    PRIMARY KEY (USER_ID,GATEWAY_ID, EMAIL),
    FOREIGN KEY (USER_ID) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (GATEWAY_ID) REFERENCES USER_PROFILE(GATEWAY_ID) ON DELETE CASCADE

) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS USER_PROFILE_PHONE (
    USER_ID VARCHAR (255) NOT NULL,
    GATEWAY_ID VARCHAR (255) NOT NULL,
    PHONE VARCHAR (255) NOT NULL,
    PRIMARY KEY (USER_ID,GATEWAY_ID, PHONE ),
    FOREIGN KEY (USER_ID) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (GATEWAY_ID) REFERENCES USER_PROFILE(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS USER_PROFILE_NATIONALITY (
    USER_ID VARCHAR (255) NOT NULL,
    GATEWAY_ID VARCHAR (255) NOT NULL,
    NATIONALITY VARCHAR (255) NOT NULL,
    PRIMARY KEY (USER_ID,GATEWAY_ID, NATIONALITY ),
    FOREIGN KEY (USER_ID) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (GATEWAY_ID) REFERENCES USER_PROFILE(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS USER_PROFILE_LABELED_URI (
    USER_ID VARCHAR (255) NOT NULL,
    GATEWAY_ID VARCHAR (255) NOT NULL,
    LABELED_URI VARCHAR (255) NOT NULL,
    PRIMARY KEY (USER_ID,GATEWAY_ID, LABELED_URI ),
    FOREIGN KEY (USER_ID) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (GATEWAY_ID) REFERENCES USER_PROFILE(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS NSF_DEMOGRAPHIC (
    USER_ID VARCHAR (255) NOT NULL,
    GATEWAY_ID VARCHAR (255) NOT NULL,
    GENDER VARCHAR (255) NOT NULL,
    PRIMARY KEY (USER_ID,GATEWAY_ID, GENDER),
    FOREIGN KEY (USER_ID) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (GATEWAY_ID) REFERENCES USER_PROFILE(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS NSF_DEMOGRAPHIC_ETHNICITY (
    USER_ID VARCHAR (255) NOT NULL,
    GATEWAY_ID VARCHAR (255) NOT NULL,
    ETHNICITY VARCHAR (255) NOT NULL,
    PRIMARY KEY (USER_ID,GATEWAY_ID, ETHNICITY ),
    FOREIGN KEY (USER_ID) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (GATEWAY_ID) REFERENCES USER_PROFILE(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS NSF_DEMOGRAPHIC_RACE (
    USER_ID VARCHAR (255) NOT NULL,
    GATEWAY_ID VARCHAR (255) NOT NULL,
    RACE VARCHAR (255) NOT NULL,
    PRIMARY KEY (USER_ID,GATEWAY_ID, RACE ),
    FOREIGN KEY (USER_ID) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (GATEWAY_ID) REFERENCES USER_PROFILE(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS NSF_DEMOGRAPHIC_DISABILITY (
    USER_ID VARCHAR (255) NOT NULL,
    GATEWAY_ID VARCHAR (255) NOT NULL,
    DISABILITY VARCHAR (255) NOT NULL,
    PRIMARY KEY (USER_ID,GATEWAY_ID, DISABILITY ),
    FOREIGN KEY (USER_ID) REFERENCES USER_PROFILE(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (GATEWAY_ID) REFERENCES USER_PROFILE(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE CONFIGURATION
(
        CONFIG_KEY VARCHAR(255) NOT NULL,
        CONFIG_VAL VARCHAR(255) NOT NULL,
        PRIMARY KEY(CONFIG_KEY, CONFIG_VAL)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO CONFIGURATION (CONFIG_KEY, CONFIG_VAL) VALUES('user_profile_catalog_version', '0.17');
