/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.custos.profile.model.user;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class user_profile_modelConstants {

  public static final String USER_PROFILE_VERSION = "1.0";

}
