-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--   http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.

-- AMIE-protocol-specific tables. Domain entities (User/Project/etc.) live in
-- core. This migration creates only the AMIE-Processor's local state.

CREATE TABLE IF NOT EXISTS amie_packets
(
    id           VARCHAR(255) NOT NULL,
    amie_id      BIGINT       NOT NULL,
    type         VARCHAR(64)  NOT NULL,
    status       VARCHAR(32)  NOT NULL,
    raw_json     TEXT         NOT NULL,
    received_at  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    decoded_at   TIMESTAMPTZ(6) NULL,
    processed_at TIMESTAMPTZ(6) NULL,
    retries      INT          NOT NULL DEFAULT 0,
    last_error   TEXT         NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_amie_packets_amie_id UNIQUE (amie_id)
);
CREATE INDEX IF NOT EXISTS idx_amie_packets_status ON amie_packets (status);
CREATE INDEX IF NOT EXISTS idx_amie_packets_received_at ON amie_packets (received_at);

CREATE TABLE IF NOT EXISTS amie_processing_events
(
    id            VARCHAR(255) NOT NULL,
    packet_id     VARCHAR(255) NOT NULL,
    type          VARCHAR(64)  NOT NULL,
    status        VARCHAR(32)  NOT NULL,
    attempts      INT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    started_at    TIMESTAMPTZ(6) NULL,
    finished_at   TIMESTAMPTZ(6) NULL,
    last_error    TEXT         NULL,
    next_retry_at TIMESTAMPTZ(6) NULL DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_amie_events_packet FOREIGN KEY (packet_id) REFERENCES amie_packets (id) ON DELETE CASCADE,
    CONSTRAINT uq_amie_events_packet_type UNIQUE (packet_id, type)
);
CREATE INDEX IF NOT EXISTS idx_amie_events_status ON amie_processing_events (status);
CREATE INDEX IF NOT EXISTS idx_amie_events_packet_id ON amie_processing_events (packet_id);
CREATE INDEX IF NOT EXISTS idx_amie_events_type ON amie_processing_events (type);
CREATE INDEX IF NOT EXISTS idx_amie_events_next_retry_at ON amie_processing_events (next_retry_at);

CREATE TABLE IF NOT EXISTS amie_processing_errors
(
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    packet_id   VARCHAR(255) NULL,
    event_id    VARCHAR(255) NULL,
    occurred_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    summary     TEXT         NOT NULL,
    detail      TEXT         NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_amie_errors_packet FOREIGN KEY (packet_id) REFERENCES amie_packets (id) ON DELETE SET NULL,
    CONSTRAINT fk_amie_errors_event FOREIGN KEY (event_id) REFERENCES amie_processing_events (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_amie_errors_packet_id ON amie_processing_errors (packet_id);
CREATE INDEX IF NOT EXISTS idx_amie_errors_event_id ON amie_processing_errors (event_id);
CREATE INDEX IF NOT EXISTS idx_amie_errors_occurred_at ON amie_processing_errors (occurred_at);

-- AMIE writes audit rows to core's audit_events table; this side table
-- carries the connector-specific references (packet_id, event_id) joined on
-- audit_event_id.
CREATE TABLE IF NOT EXISTS amie_audit_extras
(
    audit_event_id VARCHAR(255) NOT NULL,
    packet_id      VARCHAR(255) NOT NULL,
    event_id       VARCHAR(255) NULL,
    PRIMARY KEY (audit_event_id),
    CONSTRAINT fk_amie_audit_extras_event  FOREIGN KEY (audit_event_id) REFERENCES audit_events(id) ON DELETE CASCADE,
    CONSTRAINT fk_amie_audit_extras_packet FOREIGN KEY (packet_id) REFERENCES amie_packets(id) ON DELETE CASCADE,
    CONSTRAINT fk_amie_audit_extras_procev FOREIGN KEY (event_id) REFERENCES amie_processing_events(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_amie_audit_extras_event_id ON amie_audit_extras (event_id);
CREATE INDEX IF NOT EXISTS idx_amie_audit_extras_packet_id ON amie_audit_extras (packet_id);

-- AMIE-side DN registry. AMIE delivers DnList fields that contain DNs across
-- the federation (not just this site's downstream cluster).
--
-- user_id references core users.id by value; no FK because connector schema
-- stays independent of core.
CREATE TABLE IF NOT EXISTS amie_user_dns
(
    id         VARCHAR(255) NOT NULL,
    user_id    VARCHAR(255) NOT NULL,
    dn         VARCHAR(512) NOT NULL,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uq_amie_user_dns_dn UNIQUE (dn)
);
CREATE INDEX IF NOT EXISTS idx_amie_user_dns_user ON amie_user_dns (user_id);
