acmeConfiguration:
  uri: acme://pebble/localhost:14000
  userKey: user.key
  domainKey: domain.key
  domainCertificate: domain-chain.crt
  domains:
    - localhost
nginxConfiguration:
  url: http://localhost:31515
  folderPath: /acme/challenge
