global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'access-amie'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          service: 'access-amie'

  - job_name: 'custos-signer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          service: 'custos-signer'
