version: "3.3"
services:
    keycloak:
      image: quay.io/keycloak/keycloak:9.0.2
      container_name: keycloak
      ports:
        - "8080:8080"
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        PROXY_ADDRESS_FORWARDING: 'true'
        DB_VENDOR: mysql
        DB_ADDR: my_sql_local
        DB_DATABASE: keycloak
        DB_USER: admin
        DB_PASSWORD: admin
      depends_on:
        - my_sql_local

    nginx:
      image: apachecustos/keycloak-nginx:latest
      ports:
        - "443:443"
      environment:
        KEYCLOAK_HOST: keycloak
        NGINX_SERVER_NAME: host.docker.internal
      depends_on:
        - keycloak

    vault:
      image: vault:1.7.0
      container_name: vault
      restart: on-failure:10
      ports:
        - "8201:8201"
        - "8200:8200"
      environment:
        VAULT_ADDR: 'http://0.0.0.0:8201'
        VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201","tls_disable":"1"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
        VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
        VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
      cap_add:
        - IPC_LOCK
      healthcheck:
        test: "vault login 00000000-0000-0000-0000-000000000000 &&
                     vault kv get secret &&
                     vault secrets disable secret &&
                     vault secrets enable -version=1 -path=secret kv &&
                     vault secrets enable -version=1 -path=resourcesecret kv"
        interval: 5s
    rest-proxy:
      image: apachecustos/custos-rest-proxy:latest
      container_name: rest-proxy
      restart: on-failure:10
#      depends_on:
#        - custos_integration_services_server
      ports:
        - "10000:50000"
    my_sql_local:
      container_name: my_sql_local
      image: mysql:8.0.31
      restart: always
      command: --character-set-server=utf8 --collation-server=utf8_general_ci
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MAX_ALLOWED_PACKET: 1073741824
      volumes:
        - ./init/mysql/scripts/bash:/docker-entrypoint-initdb.d
        - ./init/mysql/scripts/sql:/tmp/sql

    custos_core_services_server:
      container_name: custos_core_server
      image: apachecustos/custos-core-services-server:1.1-SNAPSHOT
      restart: always
      depends_on:
        - keycloak
        - vault
        - my_sql_local
      ports:
           - "7001:7001"
           - "9001:9001"

    custos_integration_services_server:
      container_name: custos_integration_server
      image: apachecustos/custos-integration-services-server:1.1-SNAPSHOT
      restart: always
      depends_on:
        - custos_core_services_server
      ports:
        - "7000:7000"
        - "9000:9000"
