apiVersion: networking.k8s.io/v1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: ${artifactId}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /tenant-management/$2
    cert-manager.io/cluster-issuer: {{ .Values.deployment.clusterIssuer }}
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /tenant-management(/|$)(.*)
            pathType: "Prefix"
            backend:
              service:
                name: tenant-management-service
                port:
                  name: envoyhttp