apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    cert-manager.io/cluster-issuer: {{ .Values.deployment.clusterIssuer }}
  name: ${artifactId}-ingress-grpc
spec:
  rules:
     - host: {{ .Values.deployment.host }}
       http:
        paths:
          - path: /org.apache.custos.tenant.management.service.TenantManagementService(/|$)(.*)
            pathType: "Prefix"
            backend:
              service:
                name: tenant-management-service
                port:
                  name: grpc

  tls:
    - hosts:
        - {{ .Values.deployment.host }}
      secretName: tls-services-secret