# slurm/slurm.conf
ClusterName=artisan
SlurmctldHost=slurmctld

AuthType=auth/munge
AuthAltTypes=auth/jwt
AuthAltParameters=jwt_key=/etc/slurm/jwt.hs256.key
CredType=cred/munge

SlurmUser=slurm
SlurmctldPort=6817
SlurmdPort=6818
StateSaveLocation=/var/spool/slurm/ctld
SlurmdSpoolDir=/var/spool/slurm/d
SwitchType=switch/none
MpiDefault=none
ProctrackType=proctrack/linuxproc
TaskPlugin=task/none
ReturnToService=2
SlurmdParameters=config_overrides

SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log

SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory
GresTypes=gpu

AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=slurmdbd
AccountingStorageTRES=gres/gpu
AccountingStorageEnforce=associations,limits,qos,safe
AccountingStoreFlags=job_comment
JobAcctGatherType=jobacct_gather/linux
JobAcctGatherFrequency=30

NodeName=c[1-2] CPUs=4 RealMemory=8000 Gres=gpu:2 State=UNKNOWN
PartitionName=compute Nodes=c[1-2] Default=YES MaxTime=INFINITE State=UP
