apiVersion: 1

datasources:
  - name: MariaDB-AMIE
    uid: mariadb-amie
    type: mysql
    access: proxy
    url: custos_db:3306
    database: access_ci
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
    editable: false
