# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import custos.server.core.CredentialStoreService_pb2 as CredentialStoreService__pb2
import custos.server.integration.IdentityManagementService_pb2 as IdentityManagementService__pb2
import custos.server.core.IdentityService_pb2 as IdentityService__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


class IdentityManagementServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.authenticate = channel.unary_unary(
        '/org.apache.custos.identity.management.service.IdentityManagementService/authenticate',
        request_serializer=IdentityService__pb2.AuthenticationRequest.SerializeToString,
        response_deserializer=IdentityService__pb2.AuthToken.FromString,
        )
    self.isAuthenticated = channel.unary_unary(
        '/org.apache.custos.identity.management.service.IdentityManagementService/isAuthenticated',
        request_serializer=IdentityService__pb2.AuthToken.SerializeToString,
        response_deserializer=IdentityService__pb2.IsAuthenticateResponse.FromString,
        )
    self.getUser = channel.unary_unary(
        '/org.apache.custos.identity.management.service.IdentityManagementService/getUser',
        request_serializer=IdentityService__pb2.AuthToken.SerializeToString,
        response_deserializer=IdentityService__pb2.User.FromString,
        )
    self.getUserManagementServiceAccountAccessToken = channel.unary_unary(
        '/org.apache.custos.identity.management.service.IdentityManagementService/getUserManagementServiceAccountAccessToken',
        request_serializer=IdentityService__pb2.GetUserManagementSATokenRequest.SerializeToString,
        response_deserializer=IdentityService__pb2.AuthToken.FromString,
        )
    self.endUserSession = channel.unary_unary(
        '/org.apache.custos.identity.management.service.IdentityManagementService/endUserSession',
        request_serializer=IdentityManagementService__pb2.EndSessionRequest.SerializeToString,
        response_deserializer=IdentityService__pb2.OperationStatus.FromString,
        )
    self.authorize = channel.unary_unary(
        '/org.apache.custos.identity.management.service.IdentityManagementService/authorize',
        request_serializer=IdentityManagementService__pb2.AuthorizationRequest.SerializeToString,
        response_deserializer=IdentityManagementService__pb2.AuthorizationResponse.FromString,
        )
    self.token = channel.unary_unary(
        '/org.apache.custos.identity.management.service.IdentityManagementService/token',
        request_serializer=IdentityService__pb2.GetTokenRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
        )
    self.getCredentials = channel.unary_unary(
        '/org.apache.custos.identity.management.service.IdentityManagementService/getCredentials',
        request_serializer=IdentityManagementService__pb2.GetCredentialsRequest.SerializeToString,
        response_deserializer=CredentialStoreService__pb2.Credentials.FromString,
        )
    self.getOIDCConfiguration = channel.unary_unary(
        '/org.apache.custos.identity.management.service.IdentityManagementService/getOIDCConfiguration',
        request_serializer=IdentityService__pb2.GetOIDCConfiguration.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
        )
    self.getAgentToken = channel.unary_unary(
        '/org.apache.custos.identity.management.service.IdentityManagementService/getAgentToken',
        request_serializer=IdentityManagementService__pb2.GetAgentTokenRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_struct__pb2.Struct.FromString,
        )
    self.endAgentSession = channel.unary_unary(
        '/org.apache.custos.identity.management.service.IdentityManagementService/endAgentSession',
        request_serializer=IdentityManagementService__pb2.EndSessionRequest.SerializeToString,
        response_deserializer=IdentityService__pb2.OperationStatus.FromString,
        )


class IdentityManagementServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def authenticate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def isAuthenticated(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getUserManagementServiceAccountAccessToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def endUserSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def authorize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def token(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getCredentials(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getOIDCConfiguration(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAgentToken(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def endAgentSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IdentityManagementServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'authenticate': grpc.unary_unary_rpc_method_handler(
          servicer.authenticate,
          request_deserializer=IdentityService__pb2.AuthenticationRequest.FromString,
          response_serializer=IdentityService__pb2.AuthToken.SerializeToString,
      ),
      'isAuthenticated': grpc.unary_unary_rpc_method_handler(
          servicer.isAuthenticated,
          request_deserializer=IdentityService__pb2.AuthToken.FromString,
          response_serializer=IdentityService__pb2.IsAuthenticateResponse.SerializeToString,
      ),
      'getUser': grpc.unary_unary_rpc_method_handler(
          servicer.getUser,
          request_deserializer=IdentityService__pb2.AuthToken.FromString,
          response_serializer=IdentityService__pb2.User.SerializeToString,
      ),
      'getUserManagementServiceAccountAccessToken': grpc.unary_unary_rpc_method_handler(
          servicer.getUserManagementServiceAccountAccessToken,
          request_deserializer=IdentityService__pb2.GetUserManagementSATokenRequest.FromString,
          response_serializer=IdentityService__pb2.AuthToken.SerializeToString,
      ),
      'endUserSession': grpc.unary_unary_rpc_method_handler(
          servicer.endUserSession,
          request_deserializer=IdentityManagementService__pb2.EndSessionRequest.FromString,
          response_serializer=IdentityService__pb2.OperationStatus.SerializeToString,
      ),
      'authorize': grpc.unary_unary_rpc_method_handler(
          servicer.authorize,
          request_deserializer=IdentityManagementService__pb2.AuthorizationRequest.FromString,
          response_serializer=IdentityManagementService__pb2.AuthorizationResponse.SerializeToString,
      ),
      'token': grpc.unary_unary_rpc_method_handler(
          servicer.token,
          request_deserializer=IdentityService__pb2.GetTokenRequest.FromString,
          response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
      ),
      'getCredentials': grpc.unary_unary_rpc_method_handler(
          servicer.getCredentials,
          request_deserializer=IdentityManagementService__pb2.GetCredentialsRequest.FromString,
          response_serializer=CredentialStoreService__pb2.Credentials.SerializeToString,
      ),
      'getOIDCConfiguration': grpc.unary_unary_rpc_method_handler(
          servicer.getOIDCConfiguration,
          request_deserializer=IdentityService__pb2.GetOIDCConfiguration.FromString,
          response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
      ),
      'getAgentToken': grpc.unary_unary_rpc_method_handler(
          servicer.getAgentToken,
          request_deserializer=IdentityManagementService__pb2.GetAgentTokenRequest.FromString,
          response_serializer=google_dot_protobuf_dot_struct__pb2.Struct.SerializeToString,
      ),
      'endAgentSession': grpc.unary_unary_rpc_method_handler(
          servicer.endAgentSession,
          request_deserializer=IdentityManagementService__pb2.EndSessionRequest.FromString,
          response_serializer=IdentityService__pb2.OperationStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'org.apache.custos.identity.management.service.IdentityManagementService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
